version: '3'
services:
  mysql_dev:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=kyros-api
      - MYSQL_DATABASE=kyros-api
      - MYSQL_USER=kyros-api
      - MYSQL_PASSWORD=kyros-api
    expose:
      - '3306'
    ports:
      - '3306:3306'